services:
  backend:
    build:
      context: ./backend
    volumes: # Hot Reloading
      - ./backend:/app # Hot Reloading
      - /app/target # Hot Reloading
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "jdbc:postgresql://database:5432/flightflexdb"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/flightflexdb"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "post"
    command: ["./mvnw", "spring-boot:run"] # Hot Reloading
    depends_on:
      - database
    networks:
      - flightflex-network

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post
      POSTGRES_DB: flightflexdb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - flightflex-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000" # Expose React development server

    ## non-hot-reloading
    # ports:
    #   - "3000:80"
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes
    command: ["npm", "start"]
    networks:
      - flightflex-network

networks:
  flightflex-network:
    name: flightflex-network
    driver: bridge

volumes:
  postgres-data:
    driver: local
