services:
  backend:
    build:
      context: ./Backend
    container_name: FF-BE
    volumes:
      - ./Backend:/app
      - ./gradle-cache:/root/.gradle
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "jdbc:postgresql://FF-DB:5432/flightflexdb"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://FF-DB:5432/flightflexdb"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "post"
      REDIS_HOST: "FF-redis"
      REDIS_PORT: "6379"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - flightflex-network

  database:
    image: postgres:15-alpine
    container_name: FF-DB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post
      POSTGRES_DB: flightflexdb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - flightflex-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: FF-redis
    ports:
      - "6379:6379"
    networks:
      - flightflex-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./FrontendVite
      target: dev
    container_name: FF-FE
    ports:
      - "3000:3000"
    volumes:
      - ./FrontendVite:/app
      - /app/node_modules
      - /app/.vite
    environment:
      - VITE_BASE_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_HMR_HOST=localhost
    stdin_open: true
    tty: true
    networks:
      - flightflex-network
    command: ["npm", "run", "dev"]

networks:
  flightflex-network:
    name: flightflex-network
    driver: bridge

volumes:
  postgres-data:
    driver: local

  # frontend:
  #   build:
  #     context: ./frontend
  #     args:
  #       REACT_APP_BASE_URL: "http://localhost:8080"
  #       WDS_SOCKET_HOST: "127.0.0.1"
  #       CHOKIDAR_USEPOLLING: "true"
  #       WATCHPACK_POLLING: "true"
  #   environment:
  #     - WDS_SOCKET_HOST=127.0.0.1
  #     - CHOKIDAR_USEPOLLING=true
  #     - WATCHPACK_POLLING=true
  #     - CHOKIDAR_INTERVAL=1000
  #     - VITE_API_BASE_URL=http://localhost:8080
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   restart: always
  #   command:
  #     ["sh", "-c", "rimraf build && rimraf node_modules/.cache && npm start"]
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     - flightflex-network
